Feature/05 acceptance tests
arbaev/qna pull request #4
Opened 2019-04-12 09:06 UTC by arbaev

2019-04-12 10:58 UTC, vkurennov requested changes

2019-04-12 10:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, only: %i[new create destroy]
Не нужно only здесь, в этом контроллере все экшены должны быть с авторизацией

2019-04-12 10:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def new
new не нужен, т.к. форма должна быть на странице вопроса, а не на отдельной.

2019-04-12 10:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question, alert: "please, enter answer's text"
нельзя делать редирект в случае ошибок валидации, так пропадет и информация об ошибках и все, что ввел пользователь. надо делать рендер той страницы, на которой была форма

2019-04-12 10:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def destroy
нужна проверка на автора, даже если такая есть в видах: легко сделать прямой запрос, в обход вида, и удалить чужой ответ

2019-04-12 10:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def question
с учетом того, что ты не пользуешься этими методами как геттерами, а только как загрузчиками, а далее - инстанс-переменным, лучше добавить глагол load/set в название методов, чтобы подчеркнуть, что это не геттеры.

2019-04-12 10:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @question ||= Question.find(params[:question_id])
если это методы-загрузчики, то мемоизация тут смысла не имеет, т.к. в каждом запросе они вызываются только один раз (впрочем, она и не мешает, она тут вообще ни не что не влияет)

2019-04-12 10:58 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def destroy
нужна проверка на автора

2019-04-12 10:58 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def question
назови `load_question` или `set_question`

2019-04-12 10:58 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +  - if answer.author == current_user
1. Тут возникает проблема n+1 запроса, т.к. для каждого ответа ты делаешь еще один запрос к базе на получение ассоциации author, хотя все данные для того, чтобы сравнить уже загружены (используй поле author_id для сравнения)
2. Такая проверка понадобится много раз ( и у тебя она уже дублируется), поэтому вынеси ее в метод `User#author_of?`

2019-04-12 10:58 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - if @question.author == current_user
Замени на вызов `User#author_of?`

2019-04-12 10:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
тут надо еще проверить связь с залогиненным юзером

2019-04-12 10:58 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
тут нужно проверить связь с залогиненным юзером

2019-04-12 10:58 UTC, vkurennov commented on spec/factories/answers.rb
>      question { nil }
а зачем заведомо невалидный ответ созадвать? Оставь здесь просто question и ассоциация будет устанавливаться автоматически. Если в тестах нужен просто ответ, не важно у какого вопроса, будет достаточно написать `create(:answer)` без указания вопроса. А если вопрос нужен конкретный, то можно его указать

2019-04-12 10:58 UTC, vkurennov commented on spec/features/answers/create_answer_spec.rb
> +      expect(page).to have_content('answer successfully created')
нужно проверить наличие ответа на странице

2019-04-12 10:58 UTC, vkurennov commented on spec/features/answers/create_answer_spec.rb
> +  given!(:answers) { create_list(:answers_list, 3, question: question, author_id: user.id) }
в фиче на создание ответов не нужно их создавать заранее. зачем?

2019-04-12 10:58 UTC, vkurennov commented on spec/features/answers/create_answer_spec.rb
> +  given!(:question) { create(:question, id: 9999, author_id: user.id) }
id не нужно задавать руками, об этом заботятся рельсы

2019-04-12 10:58 UTC, vkurennov commented on spec/features/answers/create_answer_spec.rb
> +      fill_in 'Body', with: answers.first.body
тут может быть ложно-положительный результат из-за ранее созданных ответов: мы не знаем, ответ на странице есть, потому что мы его только что создали или потому что он уже был в базе. Поэтому нужно вводить данные, которых заведомо нет на странице

2019-04-12 10:58 UTC, vkurennov commented on spec/features/answers/create_answer_spec.rb
> +      expect(page).to have_content("please, enter answer's text")
нет, надо провериьть наличие ошибок валидации. и у DSL-методов, таких как have_content cкобки не ставятся

2019-04-12 10:58 UTC, vkurennov commented on spec/features/answers/delete_answer_spec.rb
> +  given!(:answer_user2) { create(:answer, question: question_user1, author_id: user2.id) }
этот объект никак не используется в тестах, зачем его создавать?

2019-04-12 10:58 UTC, vkurennov commented on spec/features/answers/show_answer_spec.rb
> +  given!(:question) { create(:question, id: 9999, author_id: user.id) }
не надо задавать id

2019-04-12 10:58 UTC, vkurennov commented on spec/features/questions/delete_question_spec.rb
> +  given(:question_user2) { create(:question, author_id: user2.id) }
этот объект никак не используется

2019-04-12 10:58 UTC, vkurennov commented on spec/features/questions/show_question_spec.rb
> +  given!(:question) { create(:question, id: 9999, author_id: user.id) }
не надо задавать id

2019-04-12 10:58 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
где тесты на ассоциации и валидации? и не забудь написать тесты перед тем, как писать метод `author_of?`

2019-04-14 08:03 UTC, arbaev commented on spec/features/answers/delete_answer_spec.rb
> +  given!(:answer_user2) { create(:answer, question: question_user1, author_id: user2.id) }
`answer_user2` используется для создания ответа от незалогиненого юзера. 
Можно его не создавать, а перелогиниваться под user2 и пытаться удалить `answer_user1`, но это дольше.

2019-04-14 08:03 UTC, arbaev commented on spec/features/questions/delete_question_spec.rb
> +  given(:question_user2) { create(:question, author_id: user2.id) }
аналогично `answer_user2`

2019-04-14 08:05 UTC, arbaev commented on app/controllers/answers_controller.rb
> +      @question.answers.destroy(@answer) # delete invalid nil answer
удаляю из памяти невалидный объект — это норм решение?

2019-04-14 08:11 UTC, arbaev commented on app/controllers/answers_controller.rb
> +      render 'questions/show'
После попытки создать невалидный ответ рендерится вьюха questions/show. А путь в браузере остаётся `/question/:id/answers`, это явно неправильно. Как это решить?

2019-04-14 08:17 UTC, arbaev commented on app/controllers/answers_controller.rb
> +  def destroy
как написать фича-тест для случая "юзер может сделать прямой запрос и удалить чужой ответ"? Ведь кликать не по чем, как-то генерировать прямой запрос?

2019-04-14 11:35 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def destroy
Такой фича-тест не нужен, потому что это не уровень фича-тестов (в них мы можем проверить только наличие/отсутсвие ссылки на странице), это надо тестировать на уровне контроллеров

2019-04-14 11:36 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      @question.answers.destroy(@answer) # delete invalid nil answer
Не очень, лучше в виде сделать проверку ответа на `persisted?`

2019-04-14 11:38 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      render 'questions/show'
"Это не баг, а фича". Не путай url запроса и рендер ответа. Ты же делаешь запрос на create, там путь как раз /question/:id/answers, но в ответ ты не редирект делаешь, а рендер, т.е. возвращаешь html-ответ, который и отображает браузер. В итоге, url верный, т.к. именно такой запрос и был сделан браузером. Бороться с этим не нужно (и не правильно), т.к. это правильное ожидаемое поведение соответсвующее HTTP-протоколу. Ну и кроме разработчиков никому вообще нет дела до url

2019-04-14 11:45 UTC, vkurennov approved these changes

2019-04-14 11:45 UTC, vkurennov commented on app/models/user.rb
> +  def author_of?(qna)
назови аргумент resource, тут не обязательно будет вопрос или ответ

2019-04-14 11:45 UTC, vkurennov commented on spec/features/questions/show_question_spec.rb
> +  given!(:answers) { create_list(:answers_list, 3, question: question, author: user) }
А зачем тут ответы, если ты их не проверяешь?

2019-04-14 11:45 UTC, vkurennov commented on spec/models/user_spec.rb
> +    it 'his question and answer' do
1. В юнит-тестах приня то правило "один тест - один exepct"
2. У тебя метод универсальный и не зависит от типа аргумента, поэтому не надо проверять на всех возможных типах, их может быть сколько угодно. Надо проверить на одном, любом.
3. Гораздо лушче записать так: `expect(user).to be_author_of(question)`. Это работает для любых методов-предикатов, достаточно перенести их вызов после to/to_not, добавить be_ и убрать вопр. знак

2019-04-14 13:29 UTC, arbaev commented on spec/features/questions/show_question_spec.rb
> +  given!(:answers) { create_list(:answers_list, 3, question: question, author: user) }
Незачем, последствия рефакторинга

2019-04-14 14:12 UTC, merged