Feature/06 ajax
arbaev/qna pull request #5
Opened 2019-04-16 08:05 UTC by arbaev

2019-04-21 10:39 UTC, vkurennov requested changes

2019-04-21 10:39 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def update
тут нужна проверка на автора

2019-04-21 10:39 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def update
нужна проверка на автора

2019-04-21 10:39 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def best_answer
1. назначение лучшего ответа - это действие над **ответом**, а не над вопросом, поэтому этот экшн должен быть в контроллере ответов.
2. Логика должна быть в модели, а контроллер лишь должен вызывать метод модели, чтобы сделать ответ лучшим
3. У тебя неверная архитектура, т.к. нарушается подчиненность связей и происходит их дублирование. У тебя и так ответы связаны с вопросом, а в текущей реализации ты еще раз их связываешь, причем, получается уже, что вопрос становидся подчиененным по отношению к ответу. Гораздо лучше сделать флаг у ответа и выставлять его для лучшего.
4. Где проверка на автора вопроса?

2019-04-21 10:39 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'PATCH #update' do
тут должен быть контекст для не-автора

2019-04-21 10:39 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +  describe 'PATCH #update' do
тут должен быть контекст для не-автора

2019-04-21 10:39 UTC, vkurennov commented on app/views/answers/destroy.js.erb
> +$('.answer-list__item[data-answer-id=<%= @answer.id %>]').bind('ajax:success', function() {
а зачем это делать через ajax:success? ты просто у элемента можешь вызвать `fadeOut()`, не нужно лишние обработчики добавлять

2019-04-21 10:39 UTC, vkurennov commented on app/views/answers/update.js.erb
> +  $('.answer-list__item[data-answer-id=<%= @answer.id %>]').append('<%= render 'shared/errors', resource: @answer %>');
почему append? это же добавит измененный ответ, а не заменит его. старый-то вариант не нужен уже, поэтому его надо заменить новым контентом

2019-04-21 10:39 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +  describe 'PATCH #best_answer' do
тут должны быть контексты для автора и для не-автора

2019-04-21 10:39 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'with valid attributes' do
если есть контекст с валидными атрибутами, то должен быть и для невалидных

2019-04-22 15:25 UTC, vkurennov requested changes

2019-04-22 15:25 UTC, vkurennov commented on app/models/answer.rb
> +    status = !self.best
т.к. тут несколько апдейтов, надо их обренуть в транзакцию, чтобы изменения были атомарными. и используй `update!` в этом случае, т.к. транзакция откатывается только в случае исключения

2019-04-22 15:25 UTC, vkurennov commented on app/models/answer.rb
> +  def best_answer_first
сделай скоуп и в нем order по полю best, только нужна обратная сортировка, чтобы true было в начале

2019-04-22 15:25 UTC, vkurennov commented on app/views/answers/best.js.erb
> +$('.answers-list').html('<%= j render @question.answers.sort_by(&:best_answer_first) %>');
такая сортировка очень медленная, т.к. работает в памяти, а нужно сделать это средствами базы (т.е. через скоуп в модели), тогда коллекция сразу будет отсортированной возвращаться

2019-04-22 16:12 UTC, arbaev commented on app/models/answer.rb
> +  def best_answer_first
мда, про скоупы я позабыл

2019-04-22 17:21 UTC, vkurennov approved these changes

2019-04-22 17:21 UTC, vkurennov commented on app/models/answer.rb
> +      question.answers.each { |a| a.update!(best: false) }
зря убрал, так опять же медленно получается, тут нужен `update_all`, несмотря на то, что он не выкидвает исключение, важно, что у нас последняя строка может его выкинуть и тогда все откатится.

2019-04-22 18:02 UTC, merged